### ISSUE TITLE
Debug Build Works Fine, But Release Build Throws Config: Unknown Error

### ISSUE THREAD

**Issue by aryanshdev** [Vungle/android-sdk-sample#5]
I am using Vungle with IronSource Mediation For Flutter. While testing with _**Debug Build**_ on real device as well as the Emulator, It works fine and is also displaying ads, But when I build the release version, it shows the following error :-

```bash
2023-12-29 15:18:40.776  5880-6247  VungleInitializer       com.CPLLabs.weathery                 E  java.lang.AbstractMethodError: abstract method "java.lang.Object java.lang.ClassValue.computeValue(java.lang.Class)"
                                                                                                    	at java.lang.ClassValue.getFromHashMap(ClassValue.java:230)
                                                                                                    	at java.lang.ClassValue.getFromBackup(ClassValue.java:212)
                                                                                                    	at java.lang.ClassValue.get(ClassValue.java:116)
                                                                                                    	at o4.s.a(Unknown Source:11)
                                                                                                    	at k4.k.a(SerializersCache.kt:1)
                                                                                                    	at k4.m.f(Serializers.kt:11)
                                                                                                    	at k4.m.e(Serializers.kt:1)
                                                                                                    	at k4.l.b(Unknown Source:0)
                                                                                                    	at com.vungle.ads.internal.network.k.config(VungleApiImpl.kt:3)
                                                                                                    	at com.vungle.ads.internal.network.j.config(VungleApiClient.kt:8)
                                                                                                    	at com.vungle.ads.internal.j.configure(VungleInitializer.kt:4)
                                                                                                    	at com.vungle.ads.internal.j.init$lambda-3(VungleInitializer.kt:3)
                                                                                                    	at com.vungle.ads.internal.j.d(Unknown Source:0)
                                                                                                    	at com.vungle.ads.internal.f.run(Unknown Source:10)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-12-29 15:18:40.779  5880-6247  VungleInitializer       com.CPLLabs.weathery                 E  Config: Unknown Error
2023-12-29 15:18:42.884  5880-6439  b                       com.CPLLabs.weathery                 E  error on execution
                                                                                                    java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: abstract method "java.lang.Object java.lang.ClassValue.computeValue(java.lang.Class)"
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
                                                                                                    	at h2.b.get(FutureResult.kt:5)
                                                                                                    	at com.vungle.ads.internal.l.getAvailableBidTokens(VungleInternal.kt:8)
                                                                                                    	at com.vungle.ads.VungleAds$a.getBiddingToken(Unknown Source:9)
                                                                                                    	at com.ironsource.adapters.vungle.VungleAdapter.getBiddingData(VungleAdapter.kt:2)
                                                                                                    	at com.ironsource.adapters.vungle.banner.VungleBannerAdapter.getBannerBiddingData(Unknown Source:11)
                                                                                                    	at com.ironsource.mediationsdk.adapter.AbstractBannerAdapter.collectBannerBiddingData(Unknown Source:10)
                                                                                                    	at com.ironsource.mediationsdk.AbstractAdapter.collectBannerBiddingData(Unknown Source:6)
                                                                                                    	at com.ironsource.mediationsdk.I.a(Unknown Source:20)
                                                                                                    	at com.ironsource.mediationsdk.bidding.a.b(Unknown Source:44)
                                                                                                    	at com.ironsource.mediationsdk.bidding.a.call(Unknown Source:0)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.AbstractMethodError: abstract method "java.lang.Object java.lang.ClassValue.computeValue(java.lang.Class)"
                                                                                                    	at java.lang.ClassValue.getFromHashMap(ClassValue.java:230)
                                                                                                    	at java.lang.ClassValue.getFromBackup(ClassValue.java:212)
                                                                                                    	at java.lang.ClassValue.get(ClassValue.java:116)
                                                                                                    	at o4.s.a(Unknown Source:11)
                                                                                                    	at k4.k.a(SerializersCache.kt:1)
                                                                                                    	at k4.m.f(Serializers.kt:11)
                                                                                                    	at k4.m.e(Serializers.kt:1)
                                                                                                    	at k4.l.b(Unknown Source:0)
                                                                                                    	at com.vungle.ads.internal.bidding.a.constructV4Token(BidTokenEncoder.kt:13)
                                                                                                    	at com.vungle.ads.internal.bidding.a.bidTokenV4(BidTokenEncoder.kt:1)
                                                                                                    	at com.vungle.ads.internal.bidding.a.encode(BidTokenEncoder.kt:2)
                                                                                                    	at com.vungle.ads.internal.l.getAvailableBidTokens$lambda-3(Unknown Source:9)
                                                                                                    	at com.vungle.ads.internal.l.a(Unknown Source:0)
                                                                                                    	at com.vungle.ads.internal.k.call(Unknown Source:2)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 

```
Using :

- Implementation

```gradle
    implementation 'com.ironsource.adapters:vungleadapter:4.3.23'
    implementation 'com.vungle:vungle-ads:7.1.0'
```

- Flutter Package : `ironsource_mediation: ^1.2.0`
- Flutter Version :  3.13.6

**Comment by aryanshdev** [comment]
After Some Research and Experimentation, I think Vungle Libraries are getting obfuscated.

Adding `minifyEnabled false` in buildTypes -> release of app/build.gradle helps solve the issue but increase app size, How do I only prevent Vungle libraries from obfuscation and not all, so my app size remains smaller? (I tried Proguard but didn't work)
